import { neon } from "@neondatabase/serverless";
import { drizzle } from "drizzle-orm/neon-http";
import * as schema from "../db/schema";
import { eq } from "drizzle-orm";

const db = drizzle(neon(process.env.DATABASE_URL!), { schema });

const CREATOR_ID = "seed-creator-001";

const PROMPTS = [
  // ── Developer Tools ────────────────────────────────────────────────────────
  {
    slug: "git-commit-message-writer",
    title: "Git Commit Message Writer — Conventional Commits",
    subtitle: "Perfect commit messages every time",
    description: "Paste your git diff or describe your changes and get a perfectly formatted Conventional Commits message with the right type, scope, and body. Never write a bad commit message again.",
    longDescription: `Bad commit messages make git history useless. This prompt follows the Conventional Commits spec (used by Angular, Vue, and thousands of OSS projects) and writes messages that:\n\n- Use the correct type: feat, fix, refactor, chore, docs, test, perf, ci\n- Include scope when relevant\n- Write a clear, imperative subject line under 72 chars\n- Add a body that explains WHY (not what)\n- Flag breaking changes with BREAKING CHANGE footer\n- Generate the full commit AND a one-liner for squashing\n\nWorks by pasting your git diff, a description of changes, or both.`,
    category: "developer-tools",
    pricingType: "free",
    priceCents: 0,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet", "gemini-1.5-flash", "claude-3-5-haiku"],
    useCases: ["Git workflow", "Code documentation", "Team standards", "CI/CD"],
    industries: ["Software", "All"],
    estimatedTimeSavedMinutes: 10,
    previewContent: `You are an expert in the Conventional Commits specification. Write a git commit message for the following changes:\n\nChanges made: [PASTE YOUR GIT DIFF OR DESCRIBE YOUR CHANGES]\nIs this a breaking change? [YES/NO]\nRelated ticket/issue: [ISSUE NUMBER or "none"]\n\nReturn: full commit message + one-liner version.`,
    fullContent: `You are an expert software engineer who writes exemplary git commit messages following the Conventional Commits 1.0.0 specification.\n\n**Changes made:** [PASTE YOUR GIT DIFF OR DESCRIBE WHAT YOU CHANGED]\n**Breaking change?** [YES / NO]\n**Related issue/ticket:** [e.g. "#123" or "JIRA-456" or "none"]\n**Additional context:** [anything that helps explain WHY this change was needed — optional]\n\n---\n\nDelivery format:\n\n## Full Commit Message\n\`\`\`\n<type>(<scope>): <subject>\n\n<body>\n\n<footer>\n\`\`\`\n\n## One-liner (for squash merges)\n\`\`\`\n<type>(<scope>): <subject>\n\`\`\`\n\n## Explanation\n[1-2 sentences explaining the choices you made]\n\n---\n\nRules:\n- Types: feat (new feature), fix (bug fix), refactor (no behavior change), perf (performance), docs, test, chore (build/deps), ci, style\n- Scope: the module/component/area affected (optional but recommended)\n- Subject: imperative mood ("add" not "added"), no period, max 72 chars\n- Body: explain WHY not what, reference issues, wrap at 72 chars\n- Footer: "BREAKING CHANGE: description" if applicable; "Closes #123" for issues\n- Never start subject with capital letter\n- Never end subject with period`,
    seoTitle: "Git Commit Message Generator — Conventional Commits",
    seoDescription: "Generate perfect Conventional Commits messages from your git diff. feat, fix, refactor — all formatted correctly.",
    seoKeywords: ["git commit message prompt", "conventional commits AI", "commit message generator"],
  },
  {
    slug: "sql-query-optimizer",
    title: "SQL Query Optimizer — Diagnose & Speed Up Slow Queries",
    subtitle: "Turn 30-second queries into milliseconds",
    description: "Paste any slow SQL query with your schema and get a full performance audit: missing indexes, N+1 detection, rewrite suggestions, and EXPLAIN plan interpretation.",
    longDescription: `Slow database queries are one of the most common production bottlenecks. This prompt acts as a senior DBA who can look at your query, understand your schema, and tell you exactly what's wrong and how to fix it.\n\nPaste your:\n- Query (SELECT, JOIN, subquery — any complexity)\n- Table schema (CREATE TABLE or simplified version)\n- EXPLAIN/EXPLAIN ANALYZE output (optional but helps)\n- Approximate row counts\n\nGet back:\n- Root cause analysis of why it's slow\n- Missing index recommendations (exact CREATE INDEX statements)\n- Query rewrite (optimized version)\n- N+1 detection if applicable\n- EXPLAIN plan interpretation\n- Expected improvement estimate\n\nWorks with PostgreSQL, MySQL, SQLite, and SQL Server.`,
    category: "developer-tools",
    pricingType: "paid",
    priceCents: 1299,
    difficulty: "intermediate",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Database optimization", "Performance tuning", "Backend dev", "DevOps"],
    industries: ["Software", "Fintech", "E-commerce", "SaaS"],
    estimatedTimeSavedMinutes: 60,
    previewContent: `You are a senior DBA. Analyze the following slow SQL query and provide a complete performance audit:\n\nDatabase: [PostgreSQL / MySQL / SQLite / SQL Server]\nQuery: [PASTE YOUR SLOW QUERY]\nSchema: [PASTE RELEVANT CREATE TABLE STATEMENTS]\nRow counts: [approx rows in each table]\nEXPLAIN output: [optional]`,
    fullContent: `You are a senior database administrator with 15+ years of experience optimizing queries at high-traffic companies. You've tuned queries on tables with billions of rows and know every PostgreSQL, MySQL, and SQL Server trick in the book.\n\nAnalyze the following slow query:\n\n**Database:** [PostgreSQL / MySQL / SQLite / SQL Server]\n**Query:**\n\`\`\`sql\n[PASTE YOUR SLOW QUERY HERE]\n\`\`\`\n**Schema (relevant tables):**\n\`\`\`sql\n[PASTE CREATE TABLE STATEMENTS]\n\`\`\`\n**Approximate row counts:**\n- table_name: X rows\n**EXPLAIN / EXPLAIN ANALYZE output:** [paste if you have it, or "not available"]\n**Current execution time:** [e.g. "~8 seconds"]\n**Database version:** [e.g. "PostgreSQL 16"]\n\n---\n\nDeliver this complete audit:\n\n## Performance Audit Report\n\n### Root Cause Analysis\n[What is actually making this query slow? Be specific — sequential scan on large table, missing index, cartesian product, etc.]\n\n### Identified Issues\n| # | Issue | Severity | Impact |\n|---|-------|----------|--------|\n| 1 | [issue] | Critical/High/Med/Low | [estimated slowdown] |\n\n### Missing Indexes\n\`\`\`sql\n-- Add these indexes:\nCREATE INDEX CONCURRENTLY idx_table_column ON table_name (column);\n[all recommended indexes with explanations]\n\`\`\`\n**Why each index helps:** [explanation per index]\n\n### Optimized Query\n\`\`\`sql\n-- Optimized version:\n[REWRITTEN QUERY]\n\`\`\`\n**What changed and why:** [line-by-line explanation of changes]\n\n### EXPLAIN Plan Interpretation\n[If EXPLAIN provided: walk through the execution plan, flag seq scans, hash joins, sorts, etc.]\n\n### N+1 Detection\n[Is this query part of an N+1 pattern? If so, how to fix it at the ORM/application level]\n\n### Expected Performance After Fix\n- Before: ~[X] seconds\n- After: ~[Y] ms (estimated [Z]x improvement)\n\n### Additional Recommendations\n[Partitioning, materialized views, connection pooling, caching layer — if applicable]`,
    seoTitle: "SQL Query Optimizer Prompt — Speed Up Slow Database Queries",
    seoDescription: "Get a full SQL performance audit: missing indexes, query rewrites, EXPLAIN analysis, and N+1 detection.",
    seoKeywords: ["SQL optimizer prompt", "slow query fix AI", "database performance prompt", "SQL index optimizer"],
  },
  {
    slug: "dockerfile-generator",
    title: "Dockerfile + Docker Compose Generator",
    subtitle: "Production-ready containers from your stack",
    description: "Describe your app stack and get a fully optimized Dockerfile with multi-stage builds, a docker-compose.yml with all services, and a .dockerignore — production-ready out of the box.",
    longDescription: `Most Dockerfiles people write are bloated, insecure, or not optimized for production. This prompt generates containers the way DevOps engineers at Google and Netflix would write them.\n\nProvide:\n- Your tech stack (Node.js, Python, Go, Next.js, etc.)\n- What services you need (DB, cache, queue)\n- Environment (dev vs production)\n\nGet:\n- Multi-stage Dockerfile (build stage + minimal runtime stage)\n- docker-compose.yml with all services, volumes, networks\n- .dockerignore file\n- Health check configurations\n- Non-root user setup (security best practice)\n- Layer caching optimization\n- Environment variable handling`,
    category: "developer-tools",
    pricingType: "paid",
    priceCents: 999,
    difficulty: "intermediate",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["DevOps", "Containerization", "CI/CD", "Deployment"],
    industries: ["Software", "SaaS", "DevOps"],
    estimatedTimeSavedMinutes: 45,
    previewContent: `You are a DevOps engineer. Generate a production-ready Dockerfile and docker-compose.yml for:\n\nApp type: [e.g. "Next.js 14 app with API routes"]\nLanguage/Runtime: [Node.js 20 / Python 3.12 / Go 1.22 / etc.]\nServices needed: [e.g. "PostgreSQL, Redis, the app itself"]\nEnvironment: [Development / Production / Both]`,
    fullContent: `You are a senior DevOps engineer who has containerized hundreds of applications for companies like Shopify, Stripe, and fast-growing startups. You follow Docker best practices: minimal images, non-root users, layer caching, multi-stage builds, and security hardening.\n\nGenerate Docker configuration for:\n\n**App type:** [e.g. "Next.js 14 full-stack app" / "FastAPI Python service" / "Go microservice"]\n**Language/Runtime version:** [e.g. "Node.js 20" / "Python 3.12" / "Go 1.22"]\n**Package manager:** [npm / yarn / pnpm / pip / poetry / go modules]\n**Services needed:** [e.g. "PostgreSQL 16, Redis 7, the main app" — list all]\n**Exposed port:** [e.g. 3000]\n**Environment:** [Development / Production / Both (I'll show dev and prod configs)]\n**Special requirements:** [e.g. "needs ffmpeg", "requires GPU", "monorepo setup", or "none"]\n\n---\n\nDeliver all files:\n\n## Dockerfile\n\`\`\`dockerfile\n# [Generated Dockerfile with comments explaining key decisions]\n[Multi-stage build]\n[Non-root user]\n[Optimized layer caching]\n[Health check]\n\`\`\`\n\n**Key decisions explained:**\n- Base image choice: [why this image]\n- Multi-stage: [what each stage does]\n- Non-root user: [security rationale]\n- Layer ordering: [caching strategy]\n\n## docker-compose.yml\n\`\`\`yaml\n# [Full compose file with all services]\n[App service]\n[Database service with volume]\n[Cache service if applicable]\n[Proper networking]\n[Environment variables]\n[Health checks with depends_on]\n\`\`\`\n\n## .dockerignore\n\`\`\`\n[Complete .dockerignore for this stack]\n\`\`\`\n\n## Environment Variables\n\`\`\`env\n# .env.example — all variables the app needs\n[Variable list with descriptions]\n\`\`\`\n\n## Deployment Commands\n\`\`\`bash\n# Build and run\n[Commands to get it running]\n\n# Production deploy\n[Production-specific commands]\n\`\`\`\n\n## Security Checklist\n- [ ] Non-root user: [status]\n- [ ] Secrets via env vars (not baked in): [status]\n- [ ] Minimal base image: [status]\n- [ ] No unnecessary ports exposed: [status]\n- [ ] .dockerignore excludes sensitive files: [status]`,
    seoTitle: "Dockerfile Generator Prompt — Production-Ready Containers",
    seoDescription: "Generate a multi-stage Dockerfile, docker-compose.yml, and .dockerignore for your stack — production-ready with security best practices.",
    seoKeywords: ["Dockerfile generator prompt", "Docker compose AI", "containerization prompt", "DevOps prompt"],
  },

  // ── Marketing ──────────────────────────────────────────────────────────────
  {
    slug: "landing-page-copy-writer",
    title: "Landing Page Copywriter — Above the Fold to CTA",
    subtitle: "Convert visitors with copy that actually sells",
    description: "Write a complete landing page from hero headline to footer CTA — using proven frameworks like AIDA, PAS, and the Jobs-to-Be-Done lens. Every section optimized for conversion.",
    longDescription: `Your landing page has 3 seconds to hook a visitor. Most pages waste them with vague headlines and feature lists. This prompt writes copy the way conversion rate experts do it.\n\nProvide your product details and get back copy for every section:\n- **Hero:** Headline + subheadline + CTA (3 variants A/B tested)\n- **Problem/Agitation:** What life looks like without your solution\n- **Solution:** How your product fixes it\n- **Features → Benefits:** Translated from engineer-speak to buyer-speak\n- **Social Proof:** Review templates and stat callouts\n- **FAQ:** The 5 objections that kill conversions, answered\n- **Final CTA:** Urgency-driven close\n\nDelivers copy you can paste directly into Webflow, Framer, or any builder.`,
    category: "marketing",
    pricingType: "paid",
    priceCents: 2499,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Landing page", "Sales page", "SaaS marketing", "Conversion optimization"],
    industries: ["SaaS", "E-commerce", "Agency", "Startup"],
    estimatedTimeSavedMinutes: 150,
    previewContent: `You are a world-class conversion copywriter. Write a complete landing page for:\n\nProduct: [WHAT IT IS]\nTarget customer: [WHO IT'S FOR]\nMain benefit: [#1 THING IT DOES FOR THEM]\nTop 3 features: [LIST]\nPrice: [PRICE POINT]\nBiggest objection: [WHAT HOLDS PEOPLE BACK FROM BUYING]`,
    fullContent: `You are a world-class conversion copywriter who has written landing pages generating $10M+ in revenue for SaaS products, courses, and physical goods. You combine the frameworks of David Ogilvy, Gary Halbert, and modern CRO science.\n\nWrite a complete landing page for:\n\n**Product name:** [NAME]\n**What it is:** [1-2 sentence description]\n**Target customer:** [WHO — their role, pain, situation]\n**Main transformation:** [Before state → After state. E.g. "Wastes 3 hours on cold emails → Books 10 meetings a week"]\n**Top 3 features:** [LIST — you'll translate these to benefits]\n**Proof points:** [Testimonials, numbers, case studies, notable customers — or "none yet"]\n**Price:** [PRICE POINT]\n**Primary CTA action:** [e.g. "Start free trial" / "Book a demo" / "Buy now"]\n**Biggest customer objection:** [What makes people not buy]\n**Tone:** [Professional / Conversational / Bold / Playful]\n\n---\n\nDeliver the complete page:\n\n## HERO SECTION\n**Headline Option A:** [Outcome-focused, specific]\n**Headline Option B:** [Problem-focused, empathetic]\n**Headline Option C:** [Bold claim / pattern interrupt]\n\n**Recommended headline:** [which one and why]\n\n**Subheadline:** [Expands the headline, adds specificity, 1-2 sentences]\n\n**Hero CTA button text:** [3 options]\n**Below-CTA microcopy:** [trust line, e.g. "No credit card required · Setup in 2 minutes"]\n\n**Social proof bar:** [logos or stats line below hero, e.g. "Trusted by 1,200+ teams"]\n\n---\n\n## PROBLEM SECTION\n**Section headline:**\n[3-5 bullet points that describe the painful current reality — each one should make the reader nod]\n\n---\n\n## SOLUTION SECTION\n**Section headline:** [Positions your product as the obvious fix]\n**Intro paragraph:** [2-3 sentences connecting the problem to your solution]\n\n---\n\n## FEATURES → BENEFITS\nFor each feature, translate to what it means for the customer:\n| Feature | Benefit (what they really care about) | Micro-headline |\n|---------|--------------------------------------|----------------|\n| [feature] | [outcome for them] | [punchy 5-word headline] |\n[3 rows minimum]\n\n**Feature section copy:** [2-3 sentences per benefit, expanded]\n\n---\n\n## SOCIAL PROOF SECTION\n**Section headline:**\n\n**Testimonial templates** (fill with real quotes or use as structure):\n- Short punchy quote (1-2 sentences) — from [role/company type]\n- Transformation story quote (3-4 sentences) — from [role/company type]\n- Specific result quote ("I went from X to Y in Z time") — from [role]\n\n**Stats callouts:** [3 numbers/stats formatted as big callout blocks]\n\n---\n\n## FAQ SECTION\n**Section headline:**\n\nThe 5 objections that kill conversions, answered:\n1. **[Objection 1 as a question]** → [Answer]\n2. **[Objection 2]** → [Answer]\n3. **[Objection 3]** → [Answer]\n4. **[Objection 4]** → [Answer]\n5. **[Objection 5]** → [Answer]\n\n---\n\n## FINAL CTA SECTION\n**Headline:** [Urgency or vision-based close]\n**Subtext:** [1-2 sentences reinforcing the transformation]\n**CTA button:** [Action-oriented text]\n**Risk reversal:** [Guarantee or refund language]\n\n---\n\n## META COPY\n**Page title tag:** [Under 60 chars, keyword-forward]\n**Meta description:** [Under 155 chars, benefit-driven]\n**OG headline:** [For social sharing]`,
    seoTitle: "Landing Page Copywriter Prompt — Hero to CTA",
    seoDescription: "Write a complete, conversion-optimized landing page: hero, problem, solution, benefits, FAQ, and CTA — ready to paste.",
    seoKeywords: ["landing page copy prompt", "copywriting AI", "conversion copy prompt", "sales page writer"],
  },
  {
    slug: "youtube-script-writer",
    title: "YouTube Script Writer — Hook, Content, CTA",
    subtitle: "Scripts that keep people watching to the end",
    description: "Write a full YouTube video script with a proven hook structure, retention-optimized body, pattern interrupts every 60 seconds, and a CTA that drives subscribers and clicks.",
    longDescription: `The YouTube algorithm rewards watch time. Watch time comes from scripts that are engineered to keep people watching — not just good information.\n\nThis prompt uses the same structural principles top creators use:\n- **The hook (0-30s):** Pattern interrupt + open loop + credibility\n- **The promise (30-60s):** What they'll learn and why it matters\n- **The body:** Chunked into tight segments with pattern interrupts every 60s\n- **Transitions:** Micro-hooks that prevent drop-off between sections\n- **The CTA:** Timed and worded for maximum subscriber/click conversion\n\nAlso generates: video title (5 variants), thumbnail concept, description with timestamps, and pinned comment.\n\nFor any niche — tech, finance, fitness, gaming, education, business.`,
    category: "marketing",
    pricingType: "paid",
    priceCents: 1999,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["YouTube", "Video content", "Creator economy", "Brand building"],
    industries: ["Creator", "Media", "Education", "Marketing"],
    estimatedTimeSavedMinutes: 120,
    previewContent: `You are a YouTube script strategist. Write a complete script for:\n\nTopic: [YOUR VIDEO TOPIC]\nTarget length: [5 / 8 / 10 / 15 minutes]\nChannel niche: [YOUR NICHE]\nTarget viewer: [WHO IS THIS FOR]\nMain takeaway: [WHAT THEY'LL LEARN]\nYour hook angle: [CURIOSITY / CONTROVERSY / STORY / SURPRISING STAT]`,
    fullContent: `You are a YouTube growth strategist and script writer who has helped channels grow from 0 to 100K+ subscribers. You understand the algorithm, retention curves, and the psychological principles that keep viewers watching.\n\nWrite a complete video script for:\n\n**Topic:** [YOUR VIDEO TOPIC]\n**Target length:** [5 / 8 / 10 / 15 minutes]\n**Channel niche:** [e.g. "personal finance for millennials" / "indie game dev" / "AI tools"]\n**Target viewer:** [WHO IS WATCHING — their situation, what they want]\n**Main takeaway:** [THE ONE THING THEY'LL LEARN OR FEEL]\n**Hook angle:** [CURIOSITY ("You're doing X wrong") / CONTROVERSY / PERSONAL STORY / SURPRISING STAT / BOLD CLAIM]\n**CTA goal:** [Subscribe / Click link in description / Buy product / Join community]\n**Your on-camera style:** [Energetic / Calm/educational / Conversational / Documentary]\n\n---\n\n## Title Options (5 variants)\n1. [Curiosity gap title]\n2. [How-to title]\n3. [Number list title]\n4. [Controversy/bold claim title]\n5. [Story-based title]\n\n**Recommended:** [which one + why]\n\n## Thumbnail Concept\n[Describe the thumbnail: background, text overlay, facial expression/visual, color scheme]\n\n---\n\n## FULL SCRIPT\n\n### HOOK (0:00 - 0:30)\n[Open with pattern interrupt — don't start with "Hey guys welcome back"]\n[Create an open loop — a question or tension that demands resolution]\n[Drop a credibility signal naturally]\n\n### PROMISE (0:30 - 1:00)\n[Tell them exactly what they'll get from watching the full video]\n[Make the payoff feel worth staying for]\n\n### INTRO / CONTEXT (1:00 - 2:00)\n[Brief setup — why this topic matters right now]\n[Light credibility / personal connection to topic]\n\n### [SECTION 1 TITLE] (~2:00 - X:00)\n[Content]\n**[PATTERN INTERRUPT at 60s mark]** — [direction: cut to b-roll / show graphic / change camera angle / ask rhetorical question]\n\n### [SECTION 2 TITLE]\n[Content]\n**[PATTERN INTERRUPT]**\n\n### [SECTION 3 TITLE]\n[Continue for all major sections]\n**[PATTERN INTERRUPT]**\n\n### MID-ROLL CTA (~halfway point)\n[Natural 15-second ask — subscribe, comment, or click — woven into content naturally]\n\n### [SECTION 4+]\n[Remaining content sections]\n\n### THE REVEAL / PAYOFF\n[Deliver on the promise made in the hook — close the open loop]\n\n### OUTRO & CTA (Final 45 seconds)\n[Summary of key points — 3 bullets max]\n[Primary CTA — specific and benefit-driven]\n[End screen prompt — what to watch next and why]\n\n---\n\n## VIDEO DESCRIPTION\n[Full YouTube description with]\n[Hook first line — the most important part]\n[Chapter timestamps]\n[Links mentioned]\n[About the channel]\n[Relevant hashtags — max 5]\n\n## PINNED COMMENT\n[First comment to pin — drives engagement, links, or continues the conversation]\n\n## Retention Optimization Notes\n[3-4 specific notes on where viewers typically drop off in this type of video and how the script addresses it]`,
    seoTitle: "YouTube Script Writer Prompt — Hook, Body, CTA",
    seoDescription: "Write a full retention-optimized YouTube script with hook, pattern interrupts, and a CTA that drives subscribers.",
    seoKeywords: ["YouTube script prompt", "video script AI", "YouTube hook writer", "content creator prompt"],
  },

  // ── Writing ────────────────────────────────────────────────────────────────
  {
    slug: "technical-documentation-writer",
    title: "Technical Documentation Writer — Docs That Devs Love",
    subtitle: "Write clear, complete technical docs from messy notes",
    description: "Transform rough technical notes, code comments, or verbal explanations into polished documentation: README files, how-to guides, architecture docs, and runbooks.",
    longDescription: `Great technical documentation is rare. Most is either too thin (\"just read the code\") or bloated and outdated. This prompt writes docs that new team members can actually use.\n\nGive it:\n- Rough notes or bullet points\n- Code snippets you want documented\n- A verbal explanation of how something works\n- An existing doc that needs to be rewritten\n\nGet back:\n- README.md with proper structure\n- How-to guides with step-by-step instructions\n- Architecture Decision Records (ADRs)\n- Runbooks for on-call engineers\n- API quick-start guides\n\nAll written to the Divio documentation system: tutorials, how-to guides, explanation, and reference.`,
    category: "writing",
    pricingType: "paid",
    priceCents: 1299,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["README", "Runbooks", "Architecture docs", "Developer guides"],
    industries: ["Software", "SaaS", "DevOps", "Platform"],
    estimatedTimeSavedMinutes: 90,
    previewContent: `You are a senior technical writer. Convert the following into polished documentation:\n\nDoc type: [README / How-to guide / Architecture doc / Runbook / API guide]\nAudience: [New engineer / External developer / On-call engineer / Product team]\nRough notes / content to document:\n[PASTE YOUR NOTES, CODE, OR DESCRIPTION HERE]`,
    fullContent: `You are a senior technical writer who has written documentation for Stripe, Twilio, and multiple successful open source projects with 10K+ GitHub stars. You follow the Divio documentation system and write docs that developers actually read.\n\n**Document type:** [README / How-to guide / Architecture Decision Record / Runbook / API quick-start / Internal wiki page]\n**Audience:** [New engineer onboarding / External API developer / On-call SRE / Product manager / All-hands]\n**Tech stack/context:** [Language, framework, service, or system being documented]\n**Rough content to document:**\n[PASTE YOUR NOTES, CODE COMMENTS, VERBAL EXPLANATION, OR EXISTING DRAFT HERE]\n**Tone:** [Formal / Conversational / Terse (bullet-heavy) / Narrative]\n\n---\n\nDeliver the polished document:\n\n[For README:]\n# Project Name\n\n> One-line description\n\n## Overview\n[What it is, what problem it solves, why you'd use it]\n\n## Quick Start\n\`\`\`bash\n[Minimal commands to get running]\n\`\`\`\n\n## Installation\n[Step-by-step with code blocks]\n\n## Usage\n[Common use cases with examples]\n\n## Configuration\n[Config options table]\n\n## API Reference (if applicable)\n[Key functions/endpoints]\n\n## Contributing\n[How to contribute]\n\n## License\n\n---\n\n[For How-to Guide:]\n# How to [accomplish specific goal]\n\n**Prerequisites:** [what they need before starting]\n**Time:** [estimated time]\n**Difficulty:** [beginner/intermediate/advanced]\n\n## Steps\n1. [Step with explanation and code if needed]\n2. [Step]\n...\n\n## Verification\n[How to confirm it worked]\n\n## Troubleshooting\n[Common issues and fixes]\n\n---\n\n[For Runbook:]\n# Runbook: [Incident/Process Name]\n\n**Severity:** [P0/P1/P2/P3]\n**On-call owner:** [Team]\n**Last updated:** [date]\n\n## Symptoms\n[What the alert looks like / what users report]\n\n## Diagnosis\n[Step-by-step investigation commands]\n\`\`\`bash\n[Commands to run]\n\`\`\`\n\n## Resolution\n[Fix steps in order]\n\n## Escalation\n[Who to page if this doesn't resolve it]\n\n## Post-Incident\n[Cleanup steps and what to file]`,
    seoTitle: "Technical Documentation Writer Prompt — READMEs, Runbooks, Guides",
    seoDescription: "Transform rough notes into polished technical docs: READMEs, how-to guides, architecture docs, and runbooks.",
    seoKeywords: ["technical documentation prompt", "README writer AI", "runbook generator", "tech docs AI"],
  },
  {
    slug: "newsletter-writer",
    title: "Newsletter Writer — Weekly Editions That Get Opened",
    subtitle: "Write a full newsletter issue in 10 minutes",
    description: "Write a complete newsletter issue in your voice — intro, 3-5 curated insights, one original take, and a CTA — formatted for Substack, Beehiiv, ConvertKit, or any ESP.",
    longDescription: `The newsletters that grow audiences have a signature style, a consistent structure, and a point of view. This prompt helps you write each issue faster without losing what makes yours worth reading.\n\nProvide:\n- Your newsletter's theme and audience\n- 3-5 links or topics you want to cover this week\n- One original opinion or hot take\n- Your voice samples\n\nGet:\n- Subject line (5 variants with predicted open rate reasoning)\n- Preview text\n- Intro hook\n- Each story written up with your commentary\n- Segue lines between sections\n- Original take section\n- CTA and close\n- Formatted for plain text and HTML\n\nWorks for: tech newsletters, business intel, creator economy, finance, productivity, and more.`,
    category: "writing",
    pricingType: "paid",
    priceCents: 1499,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Newsletter", "Email list", "Content marketing", "Thought leadership"],
    industries: ["Creator", "Media", "SaaS", "Consulting"],
    estimatedTimeSavedMinutes: 60,
    previewContent: `You are a newsletter editor. Write a full issue for:\n\nNewsletter name: [NAME]\nNiche/theme: [TOPIC]\nAudience: [WHO READS IT]\nThis week's stories/topics: [LIST 3-5 LINKS OR IDEAS]\nYour hot take this issue: [YOUR OPINION]\nVoice sample: [PASTE 2-3 SENTENCES IN YOUR VOICE]`,
    fullContent: `You are a professional newsletter editor who has grown publications to 50K+ subscribers in niches including tech, finance, business, and creator economy. You write in the author's voice, not generic AI voice.\n\nWrite a complete newsletter issue:\n\n**Newsletter name:** [NAME]\n**Niche/Theme:** [WHAT IT COVERS]\n**Audience:** [WHO READS IT — their role, interests, what they want to learn]\n**Frequency:** [Weekly / Twice-weekly / Daily]\n**Issue number/date:** [e.g. "Issue #47 — July 2026"]\n**This week's stories/topics:**\n1. [Link or topic + 1 sentence on why it's interesting]\n2. [Link or topic]\n3. [Link or topic]\n4. [Optional]\n5. [Optional]\n**Your original take this issue:** [YOUR OPINION, HOT TAKE, OR INSIGHT — even a rough thought is fine]\n**Voice samples:** [PASTE 2-3 SENTENCES YOU'VE WRITTEN — can be from previous issues, tweets, or emails]\n**CTA goal:** [Subscribe growth / product promo / community / sponsors]\n\n---\n\nDeliver the complete issue:\n\n## Subject Lines (5 options)\n1. [Curiosity-driven]\n2. [Benefit-driven]\n3. [News hook]\n4. [Personal/opinionated]\n5. [Number/list format]\n**Recommended + why:** [pick one and explain]\n\n## Preview Text\n[45-90 characters — the line after subject in inbox]\n\n---\n\n## FULL ISSUE\n\n**[NEWSLETTER NAME] — Issue #X**\n\n[INTRO — 2-3 sentences. Reference something timely. Open with personality, not "welcome to this week's issue."]\n\n---\n\n### [STORY 1 TITLE]\n[Your take on the story — 3-5 sentences. What happened, why it matters, your angle. Not a summary — an opinion.]\n[Source/link placeholder]\n\n---\n\n### [STORY 2 TITLE]\n[Same format]\n\n---\n\n### [STORY 3 TITLE]\n[Same format]\n\n---\n\n### MY TAKE: [HOT TAKE HEADLINE]\n[Original opinion section — 100-200 words. This is the most valuable part. Make it specific, mildly controversial, and end with a question that invites reply.]\n\n---\n\n### QUICK HITS\n[2-3 one-liners — smaller items that don't need a full section]\n• [Item]\n• [Item]\n• [Item]\n\n---\n\n[CLOSE — 2-3 sentences. Conversational sign-off. Feel free to be human — what you're working on, reading, thinking about.]\n\n[NAME]\n\n[CTA — one clean ask, naturally worded]\n\n---\n\n## Formatting Notes\n[Any platform-specific formatting tips for Substack / Beehiiv / ConvertKit]`,
    seoTitle: "Newsletter Writer Prompt — Full Issue in 10 Minutes",
    seoDescription: "Write a complete newsletter issue in your voice: subject lines, stories with commentary, original take, and CTA.",
    seoKeywords: ["newsletter writer prompt", "Substack writing AI", "newsletter content prompt", "email newsletter AI"],
  },
  {
    slug: "job-description-writer",
    title: "Job Description Writer — Attract A-Players",
    subtitle: "Write JDs that top candidates actually apply to",
    description: "Write a compelling, bias-reduced job description that attracts the right candidates — clear role expectations, honest culture signals, and compensation transparency built in.",
    longDescription: `Most job descriptions scare away great candidates with corporate jargon, laundry-list requirements, and vague culture descriptions. This prompt writes JDs that perform.\n\nResearch-backed features:\n- Opens with impact (why this role matters) not a company boilerplate\n- Requirements split into must-have vs. nice-to-have (removes qualification inflation)\n- Bias-reducing language (removes gendered words, inflated year requirements)\n- Honest compensation range (increases qualified applicant volume)\n- Real culture signals (not \"fast-paced\" and \"collaborative\")\n- Interview process transparency (reduces candidate drop-off)\n\nWorks for: engineering, design, product, marketing, sales, operations, and executive roles.`,
    category: "writing",
    pricingType: "paid",
    priceCents: 999,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Recruiting", "HR", "Hiring", "People ops"],
    industries: ["All"],
    estimatedTimeSavedMinutes: 45,
    previewContent: `You are an expert technical recruiter and hiring strategist. Write a compelling job description for:\n\nRole title: [JOB TITLE]\nTeam/company: [COMPANY NAME + WHAT IT DOES]\nLevel: [IC1-IC7 / Junior / Mid / Senior / Staff / Principal]\nMust-have skills: [LIST]\nNice-to-have: [LIST]\nComp range: [RANGE or "competitive"]\nRemote policy: [Remote / Hybrid / Onsite — location]`,
    fullContent: `You are an expert technical recruiter and people strategist who has helped companies like Linear, Notion, and fast-growing startups hire exceptional talent. You know that great JDs attract great candidates — and that most JDs repel them.\n\nWrite a job description for:\n\n**Role title:** [JOB TITLE]\n**Team/Company:** [COMPANY NAME — what it does in one sentence]\n**Company stage:** [Seed / Series A / Series B / Growth / Public]\n**Level:** [Junior / Mid / Senior / Staff / Principal / Director / VP]\n**Team size:** [The team this person joins]\n**Reports to:** [Title]\n**Must-have requirements:** [LIST — the non-negotiables]\n**Nice-to-have:** [LIST — things that'd be great but not required]\n**Day-to-day responsibilities:** [BULLET LIST of main work]\n**Impact in first 90 days:** [WHAT DOES SUCCESS LOOK LIKE]\n**Compensation range:** [RANGE — or "competitive, share if you want candidates to see it"]\n**Equity:** [Range or "yes/no"]\n**Remote policy:** [Fully remote / Hybrid X days / Onsite — city]\n**Interview process:** [Steps — e.g. "Screen → Technical → Team → Offer"]\n**One honest thing about working here:** [A real culture truth — can be a challenge or a perk]\n\n---\n\nDeliver the complete JD:\n\n# [ROLE TITLE] at [COMPANY]\n\n## The Role\n[2-3 sentences: what this person will do and why it matters to the company's mission. Lead with impact, not "we are looking for".]\n\n## What You'll Do\n[5-7 bullet points — specific, active, outcome-oriented. Not "responsible for" — use "you'll build", "you'll own", "you'll lead"]\n\n## What We're Looking For\n\n**Must have:**\n[4-6 bullets — real requirements only. Avoid "5+ years" for skills that can be demonstrated in 2. No gendered language.]\n\n**Nice to have:**\n[3-4 bullets — genuinely optional]\n\n## About [COMPANY]\n[3-4 sentences: mission, traction, what makes it interesting to work here. Specific > vague. "$X ARR" beats "fast-growing".]\n\n## Compensation\n[Salary range + equity + benefits — be specific. Candidates who see ranges are 30% more likely to apply.]\n\n## How We Work\n[3-4 honest bullet points about culture — working hours, async vs sync, how decisions get made. Avoid "we work hard and play hard."]\n\n## Our Interview Process\n[Step-by-step — how long it takes, what each stage involves. Transparency reduces drop-off.]\n\n---\n\n## Inclusive Language Audit\n[Flag any potentially exclusionary language and suggest fixes]`,
    seoTitle: "Job Description Writer Prompt — Attract Top Candidates",
    seoDescription: "Write bias-reduced, compelling job descriptions that attract A-players with honest comp, clear requirements, and real culture signals.",
    seoKeywords: ["job description prompt", "JD writer AI", "recruiting copy AI", "hiring description generator"],
  },

  // ── Data Analysis ──────────────────────────────────────────────────────────
  {
    slug: "data-analyst-python",
    title: "Data Analyst — Python EDA in One Shot",
    subtitle: "Paste your dataset description, get full analysis code",
    description: "Describe your dataset and analysis goal and get complete Python code for exploratory data analysis: cleaning, visualizations, statistical tests, and insights — ready to run in Jupyter.",
    longDescription: `Stop spending half your analysis time on boilerplate. This prompt generates production-quality EDA code that goes from raw CSV to actionable insights.\n\nDescribe your:\n- Dataset structure and column types\n- Business question you're trying to answer\n- Any known data quality issues\n\nGet back Python code covering:\n- Data loading and initial inspection\n- Missing value analysis and imputation strategy\n- Distribution analysis (histograms, box plots, violin plots)\n- Correlation analysis (heatmap + interpretation)\n- Statistical significance tests (t-test, chi-square, ANOVA — whichever applies)\n- Outlier detection\n- Key insights summary with business interpretation\n- Matplotlib/Seaborn visualizations with proper labels\n\nAll code is modular, commented, and runs in Jupyter Notebook.`,
    category: "data-analysis",
    pricingType: "paid",
    priceCents: 1999,
    difficulty: "intermediate",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Data analysis", "EDA", "Data science", "Business intelligence"],
    industries: ["Data", "Finance", "E-commerce", "Healthcare", "SaaS"],
    estimatedTimeSavedMinutes: 90,
    previewContent: `You are a senior data scientist. Write complete Python EDA code for:\n\nDataset description: [DESCRIBE YOUR DATA — columns, types, approximate size]\nBusiness question: [WHAT ARE YOU TRYING TO ANSWER]\nTarget variable: [IF SUPERVISED — what you're predicting, or "exploratory only"]\nKnown issues: [ANY DATA QUALITY PROBLEMS YOU'RE AWARE OF]\nOutput format: [Jupyter Notebook / Python script]`,
    fullContent: `You are a senior data scientist with 10+ years of experience doing EDA at companies like Airbnb, Spotify, and top analytics consultancies. You write clean, well-commented Python that junior analysts can understand and senior analysts can trust.\n\nWrite complete EDA code for:\n\n**Dataset description:** [DESCRIBE YOUR DATA — column names, data types, approximate row count, what each row represents]\n**Business question:** [WHAT ARE YOU TRYING TO UNDERSTAND OR DECIDE]\n**Target variable:** [IF SUPERVISED LEARNING — column to predict; or "exploratory only"]\n**Known data issues:** [Nulls, duplicates, outliers, encoding issues — or "unknown"]\n**Libraries preference:** [Standard: pandas + matplotlib + seaborn / or: polars + plotly / or: your preference]\n**Output format:** [Jupyter Notebook cells / Single Python script]\n\n---\n\nDeliver complete, runnable code:\n\n\`\`\`python\n# ============================================================\n# Exploratory Data Analysis — [DATASET NAME]\n# Business Question: [QUESTION]\n# ============================================================\n\n# CELL 1: Imports & Setup\nimport pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nfrom scipy import stats\nimport warnings\nwarnings.filterwarnings('ignore')\n\n# Plotting config\nplt.style.use('seaborn-v0_8')\nplt.rcParams['figure.figsize'] = (12, 6)\n\n# CELL 2: Load Data\n# [Generated loading code with common format handling]\n\n# CELL 3: Initial Inspection\n# [Shape, dtypes, head, describe — with interpretation comments]\n\n# CELL 4: Missing Value Analysis\n# [Missing value heatmap + percentage table + imputation strategy]\n\n# CELL 5: Distribution Analysis\n# [Histograms for numeric, bar charts for categorical]\n\n# CELL 6: Outlier Detection\n# [IQR method + z-score + visualization]\n\n# CELL 7: Correlation Analysis\n# [Heatmap + top correlated pairs + interpretation]\n\n# CELL 8: [Target variable analysis if applicable]\n# [Distribution, class balance, relationship with features]\n\n# CELL 9: Statistical Tests\n# [Appropriate tests based on data types and question]\n\n# CELL 10: Key Findings Summary\n# [Print formatted insights with business interpretation]\n\`\`\`\n\n## Analysis Notes\n[Explanation of statistical test choices and what the results mean in plain English]\n\n## Next Steps\n[What to investigate further based on what this EDA will likely reveal]`,
    seoTitle: "Python EDA Code Generator Prompt — Data Analysis",
    seoDescription: "Generate complete Python EDA code from your dataset description: cleaning, visualizations, stats tests, and insights.",
    seoKeywords: ["Python data analysis prompt", "EDA code generator", "pandas analysis prompt", "data science AI"],
  },
  {
    slug: "spreadsheet-formula-builder",
    title: "Spreadsheet Formula Builder — Excel & Google Sheets",
    subtitle: "Describe what you need, get the exact formula",
    description: "Describe your spreadsheet problem in plain English and get the exact Excel or Google Sheets formula — no matter how nested or complex — with a step-by-step explanation.",
    longDescription: `Spreadsheet formulas are their own language. XLOOKUP, LAMBDA, INDEX/MATCH, array formulas — most people know basic SUM and IF but get stuck on anything complex.\n\nThis prompt translates your plain-English goal into the exact formula you need, working for:\n- Lookups and references (VLOOKUP, XLOOKUP, INDEX/MATCH)\n- Conditional aggregation (SUMIFS, COUNTIFS, AVERAGEIFS)\n- Date and time calculations\n- Text manipulation and parsing\n- Array formulas and dynamic ranges\n- LAMBDA and LET for reusable logic\n- Cross-sheet and cross-workbook references\n- Power Query M code\n- Google Sheets-specific functions (QUERY, IMPORTRANGE, ARRAYFORMULA)\n\nEvery formula comes with a cell-by-cell breakdown so you understand it, not just copy it.`,
    category: "data-analysis",
    pricingType: "free",
    priceCents: 0,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet", "gemini-1.5-flash", "claude-3-5-haiku"],
    useCases: ["Spreadsheets", "Finance", "Operations", "Data analysis"],
    industries: ["All"],
    estimatedTimeSavedMinutes: 20,
    previewContent: `You are a spreadsheet expert. Give me the exact formula for:\n\nSpreadsheet app: [Excel / Google Sheets]\nWhat I want to do: [DESCRIBE IN PLAIN ENGLISH]\nMy data layout: [e.g. "Column A has dates, B has sales rep names, C has revenue"]\nWhere to put the formula: [e.g. "Cell D2"]`,
    fullContent: `You are a spreadsheet expert with mastery of both Excel and Google Sheets, including modern functions like XLOOKUP, LAMBDA, LET, dynamic arrays, and Power Query.\n\nBuild a formula for:\n\n**Spreadsheet app:** [Excel (which version?) / Google Sheets]\n**What I want to do:** [DESCRIBE IN PLAIN ENGLISH — be as specific as possible]\n**My data layout:**\n- Column A: [what's here]\n- Column B: [what's here]\n- [etc.]\n**Where the formula goes:** [e.g. "Cell D2, to be dragged down column D"]\n**Sample data (optional):** [a few example rows helps me give you the exact formula]\n\n---\n\nDeliver:\n\n## The Formula\n\`\`\`\n[EXACT FORMULA — ready to paste]\n\`\`\`\n\n## How It Works — Step by Step\n| Part | What it does |\n|------|-------------|\n| [each function/argument] | [plain English explanation] |\n\n## How to Use It\n[Where to paste it, any adjustments needed (absolute vs relative references, dragging behavior)]\n\n## Alternative Approaches\n[If there are simpler or more compatible alternatives, show them]\n\`\`\`\n[Alternative formula]\n\`\`\`\n[When to use this instead]\n\n## Edge Cases\n[What happens if the value isn't found / there are blanks / there are duplicates — and how the formula handles it]\n\n## Version Compatibility Note\n[If this uses a function only available in Excel 365 / Google Sheets / newer versions — call it out]`,
    seoTitle: "Excel & Google Sheets Formula Builder Prompt",
    seoDescription: "Describe your spreadsheet problem in plain English and get the exact formula with a step-by-step explanation.",
    seoKeywords: ["Excel formula prompt", "Google Sheets formula AI", "spreadsheet formula generator", "XLOOKUP help AI"],
  },

  // ── Productivity ────────────────────────────────────────────────────────────
  {
    slug: "weekly-review-system",
    title: "Weekly Review System — GTD-Inspired Planning",
    subtitle: "Close the week strong and own the next one",
    description: "A structured weekly review and planning prompt that processes your open loops, clears your head, reviews your goals, and builds a focused plan for the week ahead.",
    longDescription: `The weekly review is the cornerstone of personal productivity — and most people skip it because they don't have a system. This prompt is that system.\n\nBased on David Allen's GTD methodology combined with modern OKR planning, it guides you through:\n\n1. **Capture & clear:** Process everything in your head, inbox, notes\n2. **Review last week:** What got done, what got dropped, what to learn\n3. **Clarify open loops:** Decisions pending, projects stuck, waiting-fors\n4. **Review your goals:** Are your weekly actions aligned with your 90-day outcomes?\n5. **Plan next week:** Time-blocked schedule with realistic priorities\n6. **Identify the one thing:** The single highest-leverage move this week\n\nTakes 30 minutes. Saves 5 hours of reactive work.`,
    category: "productivity",
    pricingType: "paid",
    priceCents: 999,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet", "gemini-1.5-pro"],
    useCases: ["Personal productivity", "GTD", "Planning", "Goal setting"],
    industries: ["All"],
    estimatedTimeSavedMinutes: 30,
    previewContent: `You are a productivity coach. Guide me through a weekly review:\n\nDate: [TODAY'S DATE]\nLast week's top priorities: [WHAT YOU PLANNED TO DO]\nWhat actually happened: [WHAT YOU DID]\nCurrent open loops: [UNDONE TASKS, PENDING DECISIONS, WORRYING THOUGHTS]\n90-day goals: [YOUR CURRENT GOALS]\nNext week's known commitments: [MEETINGS, DEADLINES, OBLIGATIONS]`,
    fullContent: `You are a world-class productivity coach who combines GTD (Getting Things Done) methodology with modern goal-setting frameworks. You help people move from reactive overwhelm to intentional execution.\n\nGuide me through my weekly review:\n\n**Date:** [TODAY'S DATE — week ending/beginning]\n**Last week's top 3 priorities:** [WHAT YOU PLANNED TO ACCOMPLISH]\n**What actually got done:** [HONEST ACCOUNTING OF THE WEEK]\n**What got dropped or delayed:** [THINGS YOU DIDN'T DO]\n**Current brain dump (open loops):** [EVERYTHING ON YOUR MIND — tasks, worries, decisions, waiting-fors, someday-maybes — just dump it]\n**Current 90-day goals:** [YOUR QUARTERLY OBJECTIVES]\n**Next week's known hard commitments:** [MEETINGS, DEADLINES, TRAVEL, OBLIGATIONS]\n**Energy forecast:** [High / Normal / Low — what's your energy situation next week]\n\n---\n\nGuide me through each phase:\n\n## Phase 1: Last Week Debrief\n**What worked:** [Based on what I shared, identify patterns in what got done]\n**What didn't work:** [Patterns in what was dropped]\n**Key learning:** [One insight to carry forward]\n**Completion rate:** [X of 3 priorities = X%]\n\n## Phase 2: Open Loop Processing\n[Take my brain dump and organize it into:]\n\n**Immediate actions (do this week):**\n- [ ] [Task]\n- [ ] [Task]\n\n**Projects (multi-step things that need a next action):**\n- [Project name] → Next action: [specific next step]\n\n**Waiting for:**\n- [Who / what I'm waiting on]\n\n**Someday/Maybe (not this week):**\n- [Items to revisit]\n\n**Decisions needed:**\n- [Pending decisions I need to make]\n\n## Phase 3: Goal Alignment Check\n[Review my 90-day goals and assess:]\n- Goal 1: [On track / Behind / At risk] — why\n- Goal 2: [Status] — why\n- Goal 3: [Status] — why\n\n**Misalignment alert:** [Are any of my planned tasks this week NOT moving my goals forward? Call it out.]\n\n## Phase 4: Next Week Plan\n\n**The One Thing:** [Single highest-leverage action this week — the one that makes everything else easier or unnecessary]\n\n**Top 3 Priorities:**\n1. [Priority — with why it matters and time estimate]\n2. [Priority]\n3. [Priority]\n\n**Daily focus suggestions:**\n- Monday: [Focus area]\n- Tuesday: [Focus area]\n- Wednesday: [Focus area]\n- Thursday: [Focus area]\n- Friday: [Focus area or wrap-up/admin]\n\n**Energy management:** [Based on energy forecast — when to do deep work, when to do admin]\n\n## Phase 5: Capture Anything Else\n[Anything I said that I should have written down somewhere specific?]\n\n## Closing Question\n[One coaching question to sit with this week — something that will make me more intentional]`,
    seoTitle: "Weekly Review System Prompt — GTD Planning",
    seoDescription: "A structured weekly review and planning prompt: process open loops, review goals, and build a focused plan for the week ahead.",
    seoKeywords: ["weekly review prompt", "GTD planning AI", "productivity system prompt", "weekly planning AI"],
  },
  {
    slug: "email-inbox-zero",
    title: "Email Triage System — Inbox Zero Protocol",
    subtitle: "Process 50 emails in 10 minutes",
    description: "Paste your email subjects/senders and get a priority-ranked triage with draft replies for the emails that need them — in your voice, ready to send.",
    longDescription: `Email is where time goes to die. This prompt treats your inbox like a triage nurse treats an ER — prioritize, delegate, defer, delete.\n\nPaste your email list (subject lines and senders are enough) and get:\n- Priority ranking (Urgent/Today/This week/Archive/Delete)\n- One-line action for each email\n- Draft replies for emails that need responses (in your voice)\n- Delegation suggestions\n- Template identification (what can be templatized)\n\nAlso generates:\n- 5 reusable reply templates based on your common email types\n- Folder/label structure recommendation\n- Rules to auto-filter recurring senders\n\nFor Gmail, Outlook, and Hey users.`,
    category: "productivity",
    pricingType: "free",
    priceCents: 0,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet", "gemini-1.5-flash", "claude-3-5-haiku"],
    useCases: ["Email management", "Inbox zero", "Productivity", "Communication"],
    industries: ["All"],
    estimatedTimeSavedMinutes: 30,
    previewContent: `You are an executive assistant. Triage my inbox and draft replies for emails that need them:\n\nMy role: [YOUR JOB TITLE]\nVoice style: [Professional / Casual / Brief]\nEmails to triage:\n[PASTE YOUR EMAIL LIST — subject + sender for each]`,
    fullContent: `You are an elite executive assistant who manages the inbox of a busy founder/executive. You know what's urgent, what can wait, what to delete, and how to write replies that close loops without creating new ones.\n\nTriage my inbox:\n\n**My role:** [YOUR JOB TITLE]\n**My voice style:** [Professional / Casual-professional / Brief and direct]\n**Email client:** [Gmail / Outlook / Hey / Apple Mail]\n**Emails to process:**\n[PASTE YOUR EMAIL LIST — format: "From: [name/company] | Subject: [subject line]" for each]\n\n---\n\nDeliver:\n\n## Priority Triage\n| Email | Priority | Action | Time needed |\n|-------|----------|--------|-------------|\n| [From/Subject] | 🔴 Urgent / 🟡 Today / 🟢 This week / ⚪ Archive / 🗑️ Delete | [1-line action] | [X min] |\n[All emails sorted by priority]\n\n**Total: [X] emails → [X] urgent, [X] today, [X] this week, [X] archive/delete**\n\n---\n\n## Draft Replies\n[For every email that needs a response:]\n\n**Email: [Subject]**\n\`\`\`\n[Draft reply — ready to send, in the user's voice, under 5 sentences]\n\`\`\`\n\n---\n\n## 5 Reusable Templates\n[Based on patterns in these emails, generate 5 templates for recurring situations]\n\n**Template 1: [Name]**\n\`\`\`\n[Template with [FILL IN] placeholders]\n\`\`\`\n\n---\n\n## Automation Recommendations\n[Rules to auto-label/filter/archive senders that appear in this inbox]\n- Auto-archive: [sender type]\n- Auto-label: [sender → label]\n- Unsubscribe: [newsletters/promotions to cut]`,
    seoTitle: "Inbox Zero Email Triage Prompt — Process 50 Emails Fast",
    seoDescription: "Triage your inbox, get priority rankings, draft replies in your voice, and email templates — all in one prompt.",
    seoKeywords: ["inbox zero prompt", "email triage AI", "email management prompt", "email reply generator"],
  },

  // ── Business ───────────────────────────────────────────────────────────────
  {
    slug: "pricing-strategy-consultant",
    title: "Pricing Strategy Consultant — Find Your Optimal Price",
    subtitle: "Stop guessing what to charge",
    description: "Answer questions about your product, customers, and competitors and get a complete pricing strategy recommendation: model, price points, tiers, and psychological anchoring.",
    longDescription: `Pricing is the highest-leverage business decision most founders get wrong. This prompt acts as a pricing strategy consultant who will help you:\n\n- Choose the right pricing model (per seat, usage-based, flat, tiered, freemium)\n- Set price points backed by value-based logic (not cost-plus guessing)\n- Design a tier structure that maximizes both conversion and ARPU\n- Use psychological pricing principles (anchoring, decoy pricing, loss aversion)\n- Position against competitors without racing to the bottom\n- Identify your expansion revenue opportunities\n\nIncludes: pricing page copy recommendations, the right CTA for each tier, and a checklist for testing your new pricing.`,
    category: "business",
    pricingType: "paid",
    priceCents: 2999,
    difficulty: "intermediate",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Pricing strategy", "SaaS pricing", "Revenue optimization", "Product strategy"],
    industries: ["SaaS", "Startup", "E-commerce", "Consulting"],
    estimatedTimeSavedMinutes: 120,
    previewContent: `You are a pricing strategy consultant. Analyze my situation and recommend an optimal pricing strategy:\n\nProduct: [WHAT YOU SELL]\nCurrent price (if any): [PRICE or "not yet launched"]\nTarget customer: [ICP]\nMain value delivered: [WHAT OUTCOME DO CUSTOMERS GET]\nCompetitors & their prices: [LIST]\nGross margin: [% or "unknown"]\nCurrent conversion rate: [% or "unknown"]`,
    fullContent: `You are a pricing strategy consultant who has advised 50+ SaaS companies, e-commerce brands, and service businesses on pricing. You've studied the research of Madhavan Ramanujam (Monetizing Innovation), Price Intelligently's benchmark data, and classical behavioral economics.\n\nAnalyze my situation and build a complete pricing strategy:\n\n**Product/service:** [WHAT YOU SELL]\n**Current pricing:** [CURRENT PRICE / MODEL or "pre-launch"]\n**Target customer (ICP):** [WHO BUYS — role, company size, industry]\n**Value delivered:** [WHAT SPECIFIC OUTCOME does a customer get? Be quantitative if possible — "saves 10 hours/week", "increases revenue 20%"]\n**Customer's alternative:** [What do they do if they don't use you? How much does THAT cost?]\n**Competitors & prices:** [Name + price for each]\n**Your gross margin:** [% or "unknown"]\n**Current metrics (if live):** [Conversion rate, ARPU, churn, top plan distribution]\n**Business goal:** [Growth (prioritize conversion) / Profitability (prioritize ARPU) / Enterprise (prioritize ACV)]\n\n---\n\nDeliver a complete pricing strategy:\n\n## Pricing Model Recommendation\n**Recommended model:** [Per seat / Usage-based / Flat monthly / Tiered / Freemium / Hybrid]\n**Why this model:** [3-4 sentences on why it fits your product and customer]\n**Why NOT the alternatives:** [Brief dismissal of other models]\n\n## Price Points\n\n### Recommended Tier Structure\n\n**[TIER 1 NAME] — $[X]/month**\n- Target customer: [who this is for]\n- What's included: [feature list]\n- Conversion goal: [get free users to pay / land SMBs / etc.]\n- Psychological role: [anchor / entry / decoy]\n\n**[TIER 2 NAME] — $[X]/month** ← [RECOMMENDED TIER]\n- Target customer:\n- What's included:\n- This should be your highest-selling tier — here's why: [reasoning]\n\n**[TIER 3 NAME] — $[X]/month or custom**\n- Target customer:\n- What's included:\n- Enterprise signals to include: [custom contract, SLA, SSO, etc.]\n\n## Pricing Psychology\n[3-4 specific psychological tactics to apply: anchoring, decoy pricing, charm pricing, loss aversion framing, etc. — with exactly how to implement each]\n\n## Competitive Positioning\n[Where you should sit relative to competitors and why — not just "we're premium" or "we're the affordable option" — be specific about the value gap]\n\n## Expansion Revenue\n[How to grow revenue from existing customers: usage limits that drive upgrades, add-ons, annual plans, etc.]\n\n## Pricing Page Recommendations\n- CTA text for each tier: [specific button copy]\n- Annual discount: [what % and how to frame it]\n- Most popular badge: [which tier and how to use it]\n- Social proof placement: [what to show and where]\n\n## 90-Day Pricing Test Plan\n[Specific A/B tests to run to validate this pricing, in order of priority]`,
    seoTitle: "Pricing Strategy Consultant Prompt — Find Your Optimal Price",
    seoDescription: "Get a complete pricing strategy: model recommendation, tier structure, psychological anchoring, and competitive positioning.",
    seoKeywords: ["pricing strategy prompt", "SaaS pricing AI", "pricing consultant prompt", "pricing model generator"],
  },

  // ── Education ──────────────────────────────────────────────────────────────
  {
    slug: "study-plan-generator",
    title: "Personalized Study Plan Generator — Learn Anything in 30 Days",
    subtitle: "A structured curriculum for any skill or subject",
    description: "Describe what you want to learn and your current level, and get a day-by-day 30-day study plan with resources, practice exercises, milestones, and a final project.",
    longDescription: `Learning without a plan is browsing. This prompt creates a structured curriculum that uses spaced repetition principles and the 70-20-10 learning model.\n\nProvide:\n- The skill or subject (coding, language, music, finance, design)\n- Your current level\n- How much time per day you can commit\n- Your learning goal (portfolio piece, job, exam, hobby)\n\nGet:\n- Week-by-week learning objectives\n- Day-by-day resources (books, courses, videos — specific, not generic)\n- Practice exercises for each week\n- Weekly check-in questions to assess progress\n- A capstone project that proves mastery\n- Spaced repetition review schedule\n- What to do if you fall behind`,
    category: "education",
    pricingType: "paid",
    priceCents: 1299,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet", "gemini-1.5-pro"],
    useCases: ["Learning", "Skill development", "Career change", "Exam prep"],
    industries: ["Education", "All"],
    estimatedTimeSavedMinutes: 60,
    previewContent: `You are an expert learning designer. Create a 30-day study plan for:\n\nSkill/subject: [WHAT YOU WANT TO LEARN]\nCurrent level: [Complete beginner / Some exposure / Intermediate]\nTime per day: [30 min / 1 hour / 2 hours]\nGoal: [WHY YOU'RE LEARNING THIS — job, project, exam, hobby]\nLearning style: [Reading / Video / Hands-on / Mixed]`,
    fullContent: `You are an expert learning designer who has built curricula for top online education platforms and corporate training programs. You combine cognitive science (spaced repetition, interleaving, retrieval practice) with practical skill-building.\n\nCreate a personalized 30-day study plan for:\n\n**Skill/Subject:** [WHAT YOU WANT TO LEARN — be specific: "Python for data analysis" not just "coding"]\n**Current level:** [Complete beginner / Some exposure / Intermediate / Advanced (filling gaps)]\n**Available time per day:** [20 min / 30 min / 1 hour / 2 hours / flexible]\n**Learning goal:** [WHY — "get a job as a data analyst", "pass the CFA exam", "build my own app", "personal interest"]\n**Deadline pressure:** [Hard deadline / Flexible / None]\n**Learning style:** [Reading heavy / Video/visual / Hands-on projects / Mixed]\n**Resources budget:** [Free only / Under $50 / Happy to invest in courses]\n\n---\n\nDeliver the complete plan:\n\n## Your 30-Day [SKILL] Learning Plan\n\n### The Goal\n[What you'll be able to do on Day 31 — specific and measurable]\n\n### Learning Principles Baked In\n- Spaced repetition: [how this plan uses it]\n- 70-20-10: [70% practice, 20% social/project, 10% formal learning]\n- Retrieval practice: [how you'll test yourself]\n\n---\n\n## Week 1: [Foundation Theme]\n**Weekly objective:** [What you'll understand/be able to do by end of week]\n\n| Day | Topic | Resource (specific) | Exercise | Time |\n|-----|-------|---------------------|----------|------|\n| 1 | [Topic] | [Book ch. X / Video URL type / Course module] | [Specific exercise] | [X min] |\n| 2 | [Topic] | [Resource] | [Exercise] | [X min] |\n| 3 | [Topic] | [Resource] | [Exercise] | [X min] |\n| 4 | [Topic] | [Resource] | [Exercise] | [X min] |\n| 5 | Review + practice | [Review method] | [Mini project] | [X min] |\n| 6-7 | Rest + spaced review | [What to review] | [Optional stretch] | Flexible |\n\n**Week 1 check-in:** [3 questions to assess if you're ready to move on]\n\n---\n\n## Week 2: [Building Theme]\n[Same format]\n\n## Week 3: [Application Theme]\n[Same format]\n\n## Week 4: [Mastery/Project Theme]\n[Same format]\n\n---\n\n## Capstone Project\n**Project:** [Specific project that proves you've learned the skill]\n**Why this project:** [What it demonstrates to yourself or others]\n**Deliverable:** [Exactly what you'll have when done]\n**How long:** [Estimated hours]\n\n---\n\n## If You Fall Behind\n[3-day catch-up protocol — what to skip, what to prioritize, how to get back on track]\n\n## After Day 30: Where to Go Next\n[The logical next 30-day plan or 3 resources to go deeper]`,
    seoTitle: "30-Day Study Plan Generator Prompt — Learn Any Skill",
    seoDescription: "Get a personalized day-by-day 30-day study plan with resources, exercises, and a capstone project for any skill.",
    seoKeywords: ["study plan prompt", "learning plan AI", "30 day learning plan", "skill development prompt"],
  },

  // ── General AI ─────────────────────────────────────────────────────────────
  {
    slug: "ai-prompt-improver",
    title: "Prompt Engineer — Improve Any Prompt Instantly",
    subtitle: "Get 10x better outputs from any AI model",
    description: "Paste any prompt and get an improved version with chain-of-thought, role assignment, output formatting, and constraints — plus an explanation of every change made.",
    longDescription: `Most people use AI at 20% of its potential because their prompts are too vague, have no structure, and don't constrain the output.\n\nThis meta-prompt turns weak prompts into engineering-grade ones by applying:\n- **Role assignment** — gives the model an expert identity\n- **Chain-of-thought** — makes it reason step by step\n- **Output format constraints** — specifies exactly what you want back\n- **Context enrichment** — adds the background needed for a good answer\n- **Negative constraints** — tells it what NOT to do\n- **Few-shot examples** — shows what good looks like\n\nEvery change is explained so you learn the principles, not just get a better prompt.\n\nWorks for: ChatGPT, Claude, Gemini, Llama, and any other LLM.`,
    category: "general",
    pricingType: "free",
    priceCents: 0,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet", "gemini-1.5-pro", "claude-3-5-haiku"],
    useCases: ["Prompt engineering", "AI productivity", "LLM optimization", "AI tools"],
    industries: ["All"],
    estimatedTimeSavedMinutes: 15,
    previewContent: `You are an expert prompt engineer. Improve the following prompt and explain every change:\n\nOriginal prompt: [PASTE YOUR PROMPT HERE]\nModel it's for: [ChatGPT / Claude / Gemini / Other]\nUse case: [WHAT YOU'RE TRYING TO ACCOMPLISH]\nWhat's wrong with current outputs: [WHAT'S MISSING OR BAD]`,
    fullContent: `You are a world-class prompt engineer who has optimized prompts for production AI systems at Fortune 500 companies and fast-growing startups. You understand the internals of large language models and know exactly which techniques produce the best results.\n\nImprove the following prompt:\n\n**Original prompt:** \n[PASTE YOUR PROMPT HERE]\n\n**Model it's for:** [ChatGPT GPT-4o / Claude 3.7 / Gemini 1.5 Pro / Other: specify]\n**What you're trying to accomplish:** [GOAL — what the ideal output looks like]\n**What's wrong with current outputs:** [TOO VAGUE / WRONG FORMAT / MISSES THE POINT / TOO LONG / HALLUCINATING / etc.]\n**Constraints:** [ANYTHING IT MUST OR MUST NOT DO]\n\n---\n\nDeliver:\n\n## Diagnosis of Original Prompt\n[What's weak about the original — be specific]\n\n## Improved Prompt\n\`\`\`\n[FULL IMPROVED PROMPT — ready to use]\n\`\`\`\n\n## Changes Made (with reasoning)\n| Change | Why it helps |\n|--------|-------------|\n| Added role assignment | [specific explanation] |\n| Added chain-of-thought instruction | [why] |\n| Specified output format | [why] |\n| Added constraints | [what constraints and why] |\n| [other changes] | [why] |\n\n## Key Principles Applied\n[3-5 prompt engineering principles you used — explained so the user learns them]\n\n## Optional: Few-Shot Version\n[If adding examples would help, provide a version with 1-2 examples baked in]\n\n## Testing Advice\n[How to evaluate if the improved prompt is actually better — what to look for in the output]`,
    seoTitle: "Prompt Improver — Make Any AI Prompt 10x Better",
    seoDescription: "Paste your prompt and get an improved version with role assignment, chain-of-thought, constraints, and explained changes.",
    seoKeywords: ["prompt engineering prompt", "improve AI prompts", "better ChatGPT prompts", "prompt optimizer"],
  },
  {
    slug: "ai-writing-detector-bypass",
    title: "Humanize AI Text — Undetectable Rewriter",
    subtitle: "Make AI-written content sound human again",
    description: "Paste AI-generated text and get a rewritten version that passes AI detectors, maintains your meaning, matches human writing patterns, and sounds like a real person wrote it.",
    longDescription: `AI detectors look for patterns: uniform sentence length, overused phrases, lack of personal voice, and predictable structure. This prompt systematically eliminates all of them.\n\nRewriting techniques applied:\n- Sentence length variation (mix of short punchy + long flowing)\n- Removal of AI clichés ("It's worth noting", "In conclusion", "Delve into")\n- Addition of personal voice markers (hedges, opinions, asides)\n- Rhythm variation through punctuation diversity\n- Idiom and colloquialism injection\n- First-person perspective anchoring\n- Strategic imperfection (the way real humans write)\n\nThe output passes GPTZero, Originality.ai, Turnitin's AI detector, and Copyleaks. For: students, content creators, marketers, and writers.`,
    category: "general",
    pricingType: "paid",
    priceCents: 1499,
    difficulty: "beginner",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Content writing", "Academic writing", "Blog posts", "Marketing copy"],
    industries: ["Education", "Media", "Marketing", "Creator"],
    estimatedTimeSavedMinutes: 20,
    previewContent: `You are an expert editor who specializes in making AI-generated text sound authentically human. Rewrite the following:\n\n[PASTE YOUR AI-GENERATED TEXT HERE]\n\nTarget audience: [WHO WILL READ THIS]\nTone to maintain: [PROFESSIONAL / CASUAL / ACADEMIC / CONVERSATIONAL]\nLength: [Keep same / Shorter / Longer is fine]`,
    fullContent: `You are a master editor and writing coach who deeply understands both how humans write and how AI detectors identify AI-generated text. Your rewrites are indistinguishable from authentic human writing.\n\n**Text to humanize:**\n[PASTE YOUR AI-GENERATED TEXT HERE]\n\n**Target audience:** [WHO READS THIS]\n**Tone:** [Professional / Casual / Academic / Conversational / Journalistic]\n**Keep meaning:** [Exactly the same / Same points but can restructure freely]\n**Voice to emulate:** [Your own / A specific style e.g. "Malcolm Gladwell" / "No preference"]\n\n---\n\n## Humanized Version\n[REWRITTEN TEXT]\n\n---\n\n## What Was Changed (and Why)\n[Brief list of the main humanization techniques applied — so you can learn to do it yourself]\n\n## AI Detector Risk Assessment\n[Which patterns from the original were highest-risk and how the rewrite addressed them]\n\n---\n\nHumanization rules applied:\n1. Vary sentence length intentionally — never 3 sentences the same length in a row\n2. Remove: "It's worth noting", "In conclusion", "Furthermore", "Delve into", "Utilize", "Leverage", "In the realm of", "It is important to"\n3. Add: genuine hedges ("I think", "to be honest", "honestly"), rhetorical questions, parenthetical asides\n4. Break grammar rules occasionally the way humans do (em dashes, sentence fragments for emphasis, etc.)\n5. Start some sentences with "And" or "But"\n6. Use contractions consistently\n7. Add one specific, concrete detail or example that feels personal\n8. Vary paragraph length — one very short paragraph (1-2 sentences) somewhere`,
    seoTitle: "Humanize AI Text — Undetectable Rewriter Prompt",
    seoDescription: "Rewrite AI-generated text to sound human and pass AI detectors. Removes AI patterns, adds voice, rhythm variation.",
    seoKeywords: ["humanize AI text prompt", "AI detector bypass", "undetectable AI writing", "rewrite AI content"],
  },

  // ── Research ───────────────────────────────────────────────────────────────
  {
    slug: "literature-review-synthesizer",
    title: "Literature Review Synthesizer — Academic Research",
    subtitle: "Turn 20 papers into a coherent research narrative",
    description: "Paste abstracts, paper titles, or key findings from multiple research papers and get a synthesized literature review with themes, gaps, contradictions, and your own analytical framing.",
    longDescription: `Writing a literature review means reading 20-50 papers, finding the threads between them, and constructing a coherent narrative. Most students and researchers spend 40+ hours on this. This prompt cuts that to hours.\n\nPaste:\n- Paper titles and abstracts (or even just bullet-point summaries)\n- Your research question\n- Your field and audience\n\nGet a literature review covering:\n- Thematic organization of the research\n- Chronological development of thinking in the field\n- Points of scholarly agreement and disagreement\n- Identified research gaps (where your research can contribute)\n- Critical analysis (what the studies do and don't show)\n- Properly formatted in-text citations framework\n- A \"state of the field\" executive summary\n\nFor: academic papers, dissertations, systematic reviews, and evidence-based reports.`,
    category: "research",
    pricingType: "paid",
    priceCents: 2499,
    difficulty: "intermediate",
    modelSupport: ["gpt-4o", "claude-3-7-sonnet"],
    useCases: ["Academic research", "Literature review", "Dissertation", "Evidence synthesis"],
    industries: ["Education", "Research", "Healthcare", "Policy"],
    estimatedTimeSavedMinutes: 180,
    previewContent: `You are an academic research synthesizer. Write a literature review from the following sources:\n\nResearch question: [YOUR RESEARCH QUESTION]\nField/discipline: [ACADEMIC FIELD]\nAudience: [Undergrad paper / Masters thesis / PhD dissertation / Journal article / Policy brief]\nSources:\n[PASTE PAPER TITLES, AUTHORS, YEARS, AND KEY FINDINGS OR ABSTRACTS]`,
    fullContent: `You are a senior academic researcher and dissertation advisor with expertise in systematic literature reviews and qualitative synthesis. You've guided PhD students through literature reviews across social sciences, STEM, medicine, and humanities.\n\nSynthesize the following into a literature review:\n\n**Research question:** [YOUR CENTRAL RESEARCH QUESTION]\n**Field/discipline:** [ACADEMIC FIELD OR SUBFIELD]\n**Audience and purpose:** [Undergrad paper / Masters thesis / PhD chapter / Journal article / Policy brief / Systematic review]\n**Required citation style:** [APA 7th / MLA 9th / Chicago / Vancouver / Harvard]\n**Sources to synthesize:**\n[PASTE EACH SOURCE — provide at minimum: Author(s), Year, Title, and 2-3 bullet points of key findings. More context = better synthesis.]\n\n---\n\nDeliver a complete literature review:\n\n## Literature Review: [FIELD/TOPIC]\n\n### State of the Field (Executive Summary)\n[3-4 paragraph overview of what the research shows, major debates, and where the field is headed]\n\n---\n\n### Thematic Organization\n\n#### Theme 1: [Major theme that emerges from the literature]\n[Synthesized discussion — not "Author A found X, Author B found Y" but "Research consistently shows X (Author A, Year; Author B, Year), though Author C found Y under conditions Z..."]\n[3-5 paragraphs, heavily synthesized]\n\n#### Theme 2: [Second major theme]\n[Same approach]\n\n#### Theme 3: [Third theme or point of contention]\n[Emphasize disagreements and contradictions here if applicable]\n\n---\n\n### Chronological Development\n[How has thinking in this field evolved? What paradigm shifts occurred and when?]\n\n---\n\n### Points of Scholarly Agreement\n[What the field broadly agrees on — with citation support]\n\n### Points of Scholarly Disagreement or Contradiction\n[Where studies conflict — and possible reasons why (methodology, population, context)]\n\n---\n\n### Critical Analysis\n**Methodological strengths in the literature:**\n**Methodological limitations:**\n**Populations underrepresented in current research:**\n**Conflating variables or confounds to note:**\n\n---\n\n### Research Gaps (Your Contribution)\n[3-5 specific gaps in the existing literature — where your research question fits and what it could contribute]\n\n1. **Gap:** [What's missing] → **Your opportunity:** [How your research addresses it]\n2. [Same format]\n\n---\n\n### Conclusion\n[2-3 paragraphs tying the literature together and positioning your study within it]\n\n---\n\n### Reference List Framework\n[All sources cited in [CITATION STYLE] format — I'll use [Author, Year] placeholders where I don't have full details; flag these for you to complete]`,
    seoTitle: "Literature Review Synthesizer Prompt — Academic Research",
    seoDescription: "Paste paper abstracts and get a synthesized literature review with themes, gaps, contradictions, and scholarly analysis.",
    seoKeywords: ["literature review prompt", "academic research AI", "research synthesis prompt", "dissertation writing AI"],
  },
];

async function seed() {
  console.log("🌱 Seeding batch 2 prompts...\n");

  let inserted = 0;
  let skipped = 0;

  for (const p of PROMPTS) {
    const existing = await db.select({ id: schema.prompts.id }).from(schema.prompts).where(eq(schema.prompts.slug, p.slug));
    if (existing.length > 0) {
      console.log(`  ↩ Skipped (exists): ${p.title}`);
      skipped++;
      continue;
    }

    await db.insert(schema.prompts).values({
      creatorId: CREATOR_ID,
      slug: p.slug,
      title: p.title,
      subtitle: p.subtitle,
      description: p.description,
      longDescription: p.longDescription,
      category: p.category,
      pricingType: p.pricingType as "free" | "paid",
      priceCents: p.priceCents,
      difficulty: p.difficulty as "beginner" | "intermediate" | "advanced",
      modelSupport: p.modelSupport,
      useCases: p.useCases,
      industries: p.industries,
      estimatedTimeSavedMinutes: p.estimatedTimeSavedMinutes,
      previewContent: p.previewContent,
      fullContent: p.fullContent,
      seoTitle: p.seoTitle,
      seoDescription: p.seoDescription,
      seoKeywords: p.seoKeywords,
      status: "published",
      publishedAt: new Date(),
      salesCount: Math.floor(Math.random() * 60) + 3,
      avgRating: (Math.random() * 0.8 + 4.1).toFixed(2),
      reviewCount: Math.floor(Math.random() * 25) + 2,
    });

    console.log(`  ✓ ${p.title} (${p.pricingType === "free" ? "FREE" : `$${(p.priceCents / 100).toFixed(2)}`})`);
    inserted++;
  }

  console.log(`\n✅ Done! ${inserted} inserted, ${skipped} skipped.`);
  console.log("🚀 Total prompts now live — visit http://localhost:3000");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
